<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="renderer" content="webkit">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="/upload/templets/default/images/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="/upload/templets/default/images/system.css">
<script src="/upload/templets/default/images/jquery/1.11.3/jquery.min.js"></script>
<script src="/upload/templets/default/images/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<!--[if lt IE 9]>
<script src="/upload/templets/default/images/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="/upload/templets/default/images/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<script>var sitePath='upload/'</script>
<script src="/upload/templets/default/images/system.js"></script>
<script src="/upload/js/common.js"></script>
<script src="/upload/js/function.js"></script>
<title>新闻中心首页_海洋CMS</title>
<meta name="keywords" content="新闻,时事,时政,国际,国内,社会,法治,聚焦,评论,文化,教育,新视点,深度,网评,专题,环球,传播,论坛,图片,军事,焦点,排行,环保,校园,法治,奇闻,真情" />
<meta name="description" content="新闻中心是海洋CMS最重要的频道之一,24小时滚动报道国内、国际及社会新闻。每日编发新闻数以万计。包括即日的国内外不同类型的新闻与评论,人物专题,图库。" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="shortcut icon" href=" /favicon.ico" /> 
</head>
<body>
<div class="sea-header hidden-xs">
<div class="container">
	<div class="row">
  	<div class="col-xs-3">
    	<a href="http://www.easyphp.top" class="sea-logo"></a>
    </div>
  	<div class="col-xs-7">
    	<form class="form-horizontal sea-search" id="sea-search" role="search" action="" method="post">
        <div class="form-group">
        	<div class="col-sm-9">
          <input type="text" class="form-control" id="searchword" name="searchword" placeholder="Search">
          </div>
          <div class="col-sm-3 sea-col-0">    
				<button type="submit" class="btn btn-default" data-module="vod" data-action="/upload/search.php">搜视频</button>		  
        		<button type="submit" class="btn btn-default btn-success" data-module="news" data-action="/upload/so.php">搜资讯</button>
				
          </div>
        </div>
      </form>
    </div><!-- /.col-xs-5 -->
  </div><!-- /.row -->
</div>
</div>
<nav class="navbar navbar-inverse visible-lg visible-md" role="navigation">
  <div class="container">
    <ul class="nav navbar-nav navbar-left">
<li class=""><a href="http://www.easyphp.top" class="dropdown-toggle" data-toggle="">首页</a></li>

        <li class="dropdown">
          <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">新闻<b class="caret"></b></a>
          <ul class="dropdown-menu">
            
			<li><a href="/upload/list/?5.html">体育</a></li>
			
			<li><a href="/upload/list/?6.html">汽车</a></li>
			
			<li><a href="/upload/list/?7.html">科技</a></li>
			
			<li><a href="/upload/list/?8.html">财经</a></li>
			
			<li><a href="/upload/list/?9.html">股市</a></li>
			
			<li><a href="/upload/list/?10.html">地方</a></li>
			
			<li><a href="/upload/list/?11.html">母婴</a></li>
			
			<li><a href="/upload/list/?12.html">生活</a></li>
			
          </ul>
        </li>

        <li class="dropdown">
          <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">娱乐<b class="caret"></b></a>
          <ul class="dropdown-menu">
            
			<li><a href="/upload/list/?13.html">明星</a></li>
			
			<li><a href="/upload/list/?14.html">音乐</a></li>
			
			<li><a href="/upload/list/?15.html">游戏</a></li>
			
			<li><a href="/upload/list/?16.html">原创</a></li>
			
          </ul>
        </li>
	


        <li class="">
          <a href="/upload/list/?3.html" class="dropdown-toggle" data-toggle="">军事</a>
        </li>

        <li class="">
          <a href="/upload/list/?4.html" class="dropdown-toggle" data-toggle="">猎奇</a>
        </li>
	
<li class=""><a href="/upload/topic/?1.html" class="dropdown-toggle" data-toggle="">专辑</a></li>
<li class=""><a href="/upload/news/" class="dropdown-toggle" data-toggle="">文章</a></li>		
<li class=""><a href="/upload/gbook.php"  class="dropdown-toggle" data-toggle="">留言求片</a></li>
<li class=""><a href="/upload/member.php" class="dropdown-toggle" data-toggle="">会员中心</a></li>
<li class=""><a href="/upload/new.html" class="dropdown-toggle" data-toggle="">最近更新</a></li>
<li class=""><a href="/upload/top/hot.html" class="dropdown-toggle" data-toggle="">热门排行</a></li>

    </ul>
  </div><!-- /.container -->
</nav><!-- /.navbar -->
<div class="container sea-nav visible-xs visible-sm">
	<div class="row">
    <ul class="list-inline">
      <li class="col-xs-3 text-left">
        <h4><a href="javascript:;" id="sea-goback"><span class="glyphicon glyphicon-chevron-left"></span></a></h4>
      </li>
      <li class="col-xs-6 text-center">
        <h4>海洋CMS</h4>
      </li>
      <li class="col-xs-3 text-right"><h4>
        <a href="http://www.easyphp.top"><span class="glyphicon glyphicon-home"></span></a>
        <a href="/search.php?searchword=请输入关键词"><span class="glyphicon glyphicon-search"></span></a></h4>
      </li>
    </ul>
  </div>
</div>

<div class="container sea-bg sea-news news-list">
<div class="row">
<div class="col-md-8 col-xs-12 sea-col">

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?17.html">国内</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?18.html">国际</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?19.html">社会</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?20.html">军事</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?21.html">娱乐</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?22.html">八卦</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?23.html">科技</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?24.html">财经</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?25.html">公益</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?26.html">评论</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

	
  	<div class="page-header">
      <h4><span class="glyphicon glyphicon-pencil sea-text"></span> <a href="/upload/articlelist/?27.html">时尚</a>
	  <small>共有<span class="sea-text">0</span>篇内容</small>
      </h4>
    </div>
    
 

  </div><!-- --> 
  
  <div class="col-md-4 sea-col visible-md visible-lg">
  	 <div class="page-header sea-border-none">
      <h4><span class="glyphicon glyphicon-th-list sea-text"></span> 相关分类</h4>
    </div>
    <ul class="row list-unstyled text-center news-item-type">
     
      <li class="col-xs-4">
        <a href="/upload/articlelist/?17.html" class="btn btn-sm btn-default btn-block">国内</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?18.html" class="btn btn-sm btn-default btn-block">国际</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?19.html" class="btn btn-sm btn-default btn-block">社会</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?20.html" class="btn btn-sm btn-default btn-block">军事</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?21.html" class="btn btn-sm btn-default btn-block">娱乐</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?22.html" class="btn btn-sm btn-default btn-block">八卦</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?23.html" class="btn btn-sm btn-default btn-block">科技</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?24.html" class="btn btn-sm btn-default btn-block">财经</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?25.html" class="btn btn-sm btn-default btn-block">公益</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?26.html" class="btn btn-sm btn-default btn-block">评论</a>
      </li>
      
      <li class="col-xs-4">
        <a href="/upload/articlelist/?27.html" class="btn btn-sm btn-default btn-block">时尚</a>
      </li>
      
    </ul>
    <div class="clearfix sea-clearfix"></div>
    <div class="page-header sea-border-none">
      <h4><span class="glyphicon glyphicon-signal sea-text"></span> 热点资讯</h4>
    </div>
    <ol class="news-item-hot">
       
    </ol>
  </div>
</div>
</div>
<div class="clearfix sea-clearfix"></div>
<div class="container sea-bg sea-footer">
  <div class="row">
    <div class="col-md-10 col-sm-12 col-xs-12">
      <p>友情提示：请勿长时间观看影视，注意保护视力并预防近视，合理安排时间，享受健康生活。</p>
      <p>网站简介：努力打造海洋影视管理系统为最好的PHP影视系统!</p>
      <p>版权声明：本网站为非赢利性站点，本网站所有内容均来源于互联网相关站点自动搜索采集信息，相关链接已经注明来源。</p>
      <p><font color="#4682B4">{seacms:runinfo}</font>，<a href="http://www.seacms.net" target="_blank"  style="color:#4682B4">Power by SeaCMS</a></p>
    </div>
    <ul class="col-md-2 hidden-sm hidden-xs">
      <li><a href="/upload/gbook.php" >留言反馈</a></li>
	  <li><a href="/upload/new.html" >最近更新</a></li>
	  <li><a href="/upload/hot/hot.html" >热门排行</a></li>
	  <li>{seacms:member}</li>
    </ul>  
  </div>
</div>
<span style="display:none"></span>
</body>
</html>